Tipos de tensores

In [ ]:
import torch # importando pytorch

lista = [[1,2,3],[4,5,6]]

tns = torch.FloatTensor(lista) #toch.Tensor(lista)
print(tns.dtype)
print(tns)

tns = torch.DoubleTensor(lista)
print(tns.dtype)
print(tns)

tns = torch.LongTensor(lista)
print(tns.dtype)
print(tns)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


Outras formar de instancia tensores

In [ ]:
import numpy as np

arr = np.random.rand(3,4)
tns = torch.from_numpy(arr)

print(arr)
print(arr.dtype)

print(tns)
print(tns.dtype)

[[0.6266158  0.47316241 0.55407222 0.79768471]
 [0.03569442 0.18987047 0.68265922 0.6530382 ]
 [0.91800032 0.05292196 0.39204099 0.91237891]]
float64
tensor([[0.6266, 0.4732, 0.5541, 0.7977],
        [0.0357, 0.1899, 0.6827, 0.6530],
        [0.9180, 0.0529, 0.3920, 0.9124]], dtype=torch.float64)
torch.float64


torch.ones() -> Cria um tensor preenchido por uns

torch.zeros() -> Cria um tensor preenchido por zeros

torch.randn() -> Cria um tensor preenchido por numeros rand

In [ ]:
tns1 = torch.ones(2,3)
tns0 = torch.zeros(4,5)
tnsr = torch.randn(3,3)

print(tns1)
print(tns0)
print(tnsr)

# tensor para array numpy
arr = tnsr.data
print(arr)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[-0.8918, -2.4944, -0.0102],
        [ 0.7263,  1.5234, -0.1938],
        [-0.8115,  0.1318, -0.8984]])
tensor([[-0.8918, -2.4944, -0.0102],
        [ 0.7263,  1.5234, -0.1938],
        [-0.8115,  0.1318, -0.8984]])


In [ ]:

if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')

print(device)

tns = tns.to(device)
print(tns)

cuda
tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')


In [ ]:
import torch
tns = torch.randn(9, 12)
tns1 = tns[0:5, 0:4]
tns2 = tns[5:, 4:]

resultado = torch.mm(tns1, tns2)
print(resultado.size())

torch.Size([5, 8])


In [ ]:
import torch

# Crie o tensor aleatório tns1 com dimensionalidade 7 x 7 x 3
tns1 = torch.rand((7, 7, 3))

# Crie o tensor aleatório tns2 com dimensionalidade 147 x 1
tns2 = torch.rand((147, 1))

# Modifique tns1 para ter a mesma dimensionalidade que tns2
# Neste caso, você pode expandir as dimensões do tensor tns1 para (7, 7, 147, 3)
tns1 = tns1.unsqueeze(2).expand(7, 7, 147, 3)

# Some os dois tensores
resultado = tns1 + tns2

# Verifique as dimensões do resultado
print(resultado.shape)
